# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  delopy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          
      - name: Deps
        run: |
            npm install --global sperm
            npm i
            
      - name: Build plugin
        run: |
          mkdir .dist
          sperm build
      - name: Copy additional files
        run: |
          cp README.md .dist/README.md
          printf -- "---\npermalink: /404.html\n---\n" > .dist/404.md
          printf -- "> **Note:** You accessed a link that returned a 404, probably by clicking one of the plugin links. You're supposed to copy the link address and add it into Cumcord.\n\n" >> .dist/404.md
          cat README.md >> .dist/404.md
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.dist
          # Makes it so the md files in the previous step get processed by GitHub Pages
          enable_jekyll: true
